### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lumon13** [GuillermoPena/private-telegram-bot#2]
I was using the Bot normally, i had canceled it with ctlr+c but after it when I'll start bot I only get 
TypeError: Cannot read property 'length' of undefined
    at Object.logger.prepareMessage (/home/minimon/private-telegram-bot/private-telegram-bot.js:26:41)
    at Bot.filterMessages (/home/minimon/private-telegram-bot/lib/bot.js:101:31)
    at null.<anonymous> (/home/minimon/private-telegram-bot/lib/bot.js:71:11)
    at emit (events.js:95:17)
    at /home/minimon/private-telegram-bot/node_modules/telegram-bot-api/lib/telegram-bot.js:122:26
    at Array.forEach (native)
    at /home/minimon/private-telegram-bot/node_modules/telegram-bot-api/lib/telegram-bot.js:115:22
    at /home/minimon/private-telegram-bot/node_modules/telegram-bot-api/lib/telegram-bot.js:723:24
    at commonResponseHandler (/home/minimon/private-telegram-bot/node_modules/telegram-bot-api/lib/telegram-bot.js:93:16)
    at Request._callback (/home/minimon/private-telegram-bot/node_modules/telegram-bot-api/lib/telegram-bot.js:721:13)

anyway for fix this?

**Comment by lumon13** [comment]
Just some error on token and machines using bot. Just generate new token on Botfather and now its working
